version: '3'
volumes:
  deploy-log:
  deploy-script:
services:
  kkitdeploy:
    image: registry.cn-hangzhou.aliyuncs.com/yangb/kkitdeploy
    container_name: kkitdeploy
    hostname: kkitdeploy
    privileged: true
    ports:
    - 80:80
    - 8002:8002
    volumes:
    - deploy-log:/var/log/
    - deploy-script:/opt/kkitDeploy/apps/utils/api/
    - ./settings.py:/opt/kkitDeploy/kkitDeploy/settings.py
    - ./conf.py:/opt/kkitDeploy/kkitDeploy/conf.py
    - ./IPConfig.js:/opt/dist/IPConfig.js
    restart: always
  redis:
    image: redis
    container_name: kkitredis
    hostname: kkitredis
    command: redis-server --requirepass root1234
    ports:
    - "6379:6379"
    volumes:
    - ./data:/data
